import test from"node:test";import assert from"node:assert/strict";import{MandateMcpServer}from"../server.js";
test("lists canonical tools with generated semantic guidance",async()=>{const s=new MandateMcpServer({request:async()=>({})}as any);const r:any=await s.handle({jsonrpc:"2.0",id:1,method:"tools/list"});assert.equal(r.result.tools.length,15);assert.ok(r.result.tools.some((t:any)=>t.name==="list_capabilities"));assert.ok(r.result.tools.some((t:any)=>t.name==="get_liquidity_status"));assert.ok(r.result.tools.some((t:any)=>t.name==="fund_spend"));assert.ok(r.result.tools.some((t:any)=>t.name==="get_funding_movement"));const checkout=r.result.tools.find((t:any)=>t.name==="create_checkout");assert.match(checkout.description,/Money should come from another party/);assert.match(checkout.description,/use pay instead/);});
test("tool calls use the canonical flat snake_case daemon contract",async()=>{let call:any[]=[];const s=new MandateMcpServer({request:async(...a:any[])=>{call=a;return{status:"ready"};}}as any);const r:any=await s.handle({jsonrpc:"2.0",id:2,method:"tools/call",params:{name:"create_checkout",arguments:{account_id:"acct",amount_atomic:"2200",currency:"USD",description:"Hosting",idempotency_key:"idem"}}});assert.deepEqual(call.slice(0,2),["POST","/v1/checkouts"]);assert.deepEqual(call[2],{account_id:"acct",amount:"2200",currency:"USD",provider:null,idempotency_key:"idem",metadata:{description:"Hosting"}});assert.equal(call[3],"idem");assert.equal(r.result.structuredContent.status,"ready");});
test("payment request is flat and preserves caller idempotency",async()=>{let body:any;const s=new MandateMcpServer({request:async(_m:string,_p:string,b:any)=>{body=b;return{};}}as any);await s.handle({jsonrpc:"2.0",id:3,method:"tools/call",params:{name:"create_payment_session",arguments:{account_id:"acct",amount_atomic:"49",currency:"usd",mode:"single_use",idempotency_key:"fixed"}}});assert.deepEqual(body,{account_id:"acct",amount:"49",currency:"USD",provider:null,idempotency_key:"fixed",metadata:{},mode:"single_use",merchant:null});});

test("whoami introspects the current credential via GET /v1/me",async()=>{let call:any[]=[];const s=new MandateMcpServer({request:async(...a:any[])=>{call=a;return{is_admin:false,account_id:"acct_1",account_name:"Primary account",capabilities:["balance"]};}}as any);const r:any=await s.handle({jsonrpc:"2.0",id:4,method:"tools/call",params:{name:"whoami",arguments:{}}});assert.deepEqual(call.slice(0,2),["GET","/v1/me"]);assert.equal(r.result.structuredContent.account_name,"Primary account");});

test("get_liquidity_status maps to GET /v1/liquidity-status with currency query",async()=>{let call:any[]=[];const s=new MandateMcpServer({request:async(...a:any[])=>{call=a;return{spendable_now:"100000",available_to_fund:"0"};}}as any);const r:any=await s.handle({jsonrpc:"2.0",id:6,method:"tools/call",params:{name:"get_liquidity_status",arguments:{account_id:"acct",currency:"USD"}}});assert.deepEqual(call.slice(0,2),["GET","/v1/liquidity-status?account_id=acct&currency=USD"]);assert.equal(r.result.structuredContent.spendable_now,"100000");});
test("fund_spend maps to POST /v1/fund-spend with a flat money body",async()=>{let call:any[]=[];const s=new MandateMcpServer({request:async(...a:any[])=>{call=a;return{state:{status:"settled"},funding_amount:"2500"};}}as any);const r:any=await s.handle({jsonrpc:"2.0",id:7,method:"tools/call",params:{name:"fund_spend",arguments:{account_id:"acct",amount_atomic:"102500",currency:"USD",idempotency_key:"idem"}}});assert.deepEqual(call.slice(0,2),["POST","/v1/fund-spend"]);assert.deepEqual(call[2],{account_id:"acct",amount:"102500",currency:"USD",provider:null,idempotency_key:"idem",metadata:{}});assert.equal(call[3],"idem");assert.equal(r.result.structuredContent.funding_amount,"2500");});
test("get_funding_movement maps to GET /v1/funding-movements/{id}",async()=>{let call:any[]=[];const s=new MandateMcpServer({request:async(...a:any[])=>{call=a;return{id:"mov_1",state:{status:"settled"}};}}as any);const r:any=await s.handle({jsonrpc:"2.0",id:8,method:"tools/call",params:{name:"get_funding_movement",arguments:{movement_id:"mov_1"}}});assert.deepEqual(call.slice(0,2),["GET","/v1/funding-movements/mov_1"]);assert.equal(r.result.structuredContent.id,"mov_1");});
test("list_capabilities discovers account-specific runtime truth",async()=>{let call:any[]=[];const s=new MandateMcpServer({request:async(...a:any[])=>{call=a;return{account_id:"acct_1",capabilities:[{id:"checkout",available:false,unavailable_reason:"Connect a Receive provider"}]};}}as any);const r:any=await s.handle({jsonrpc:"2.0",id:5,method:"tools/call",params:{name:"list_capabilities",arguments:{account_id:"acct_1"}}});assert.deepEqual(call.slice(0,2),["GET","/v1/capabilities?account_id=acct_1"]);assert.equal(r.result.structuredContent.capabilities[0].available,false);});
