// Generated by scripts/generate-capabilities.mjs. Do not edit.
export type Capability = "money.fiat_to_stablecoin" | "money.stablecoin_to_fiat" | "revenue.checkout" | "revenue.invoice" | "revenue.refund" | "spending.card" | "spending.card.revoke" | "treasury.balance" | "treasury.receive" | "treasury.transfer";

export const PROVIDER_CAPABILITIES = [
  "money.fiat_to_stablecoin",
  "money.stablecoin_to_fiat",
  "revenue.checkout",
  "revenue.invoice",
  "revenue.refund",
  "spending.card",
  "spending.card.revoke",
  "treasury.balance",
  "treasury.receive",
  "treasury.transfer"
] as const;
