import { JsonValue, ProviderContext, ProviderError, ProviderHealth, ProviderManifest, ProviderOperation, ProviderPlugin, ProviderResult, SyncPage, providerFetch, requireStrings } from "@mandate/provider-sdk";
type Config={mode:"mock"|"sandbox"|"live";apiKey?:string;baseUrl:string;accountToken?:string};const defaults:Config={mode:"mock",baseUrl:"https://sandbox.lithic.com"};
export class LithicCardPlugin implements ProviderPlugin{
 readonly manifest:ProviderManifest={id:"lithic-card",displayName:"Lithic Cards",version:"0.1.0",protocolVersion:"1.0",capabilities:["spending.card","spending.card.revoke"],assets:[],networks:[],currencies:["USD"],regions:["US"],environments:["sandbox","live"],configurationSchema:{type:"object",properties:{mode:{enum:["mock","sandbox","live"]},apiKey:{type:"string"},accountToken:{type:"string"}}},secretFields:["apiKey","pan","cvv","cvc"],healthChecks:["authentication","card_program"]};
 private config:Config=defaults;private active=false;
 async validateConfiguration(input:Record<string,JsonValue>){const c={...defaults,...input}as Config;const errors=c.mode==="mock"?[]:requireStrings(input,["apiKey"]);if(c.mode==="sandbox"&&!c.baseUrl.startsWith("https://sandbox.lithic.com"))errors.push("sandbox must use sandbox.lithic.com");if(c.mode==="live"&&!c.baseUrl.startsWith("https://api.lithic.com"))errors.push("live must use api.lithic.com");return{valid:!errors.length,errors};}
 async initialize(input:Record<string,JsonValue>){const v=await this.validateConfiguration(input);if(!v.valid)throw new ProviderError({code:"invalid_configuration",message:v.errors.join("; "),retryable:false});this.config={...defaults,...input}as Config;this.active=true;return this.health();}
 async capabilities(){return this.manifest.capabilities;}private headers(ctx?:ProviderContext){return{Authorization:String(this.config.apiKey),Accept:"application/json","Content-Type":"application/json",...(ctx?.idempotencyKey?{"Idempotency-Key":ctx.idempotencyKey}:{})};}
 private request(path:string,init:RequestInit={}){return providerFetch(`${this.config.baseUrl}${path}`,{...init,headers:{...this.headers(),...(init.headers as Record<string,string>|undefined)}});}
 async health():Promise<ProviderHealth>{if(!this.active)return{state:"disconnected",checkedAt:new Date().toISOString()};if(this.config.mode==="mock")return{state:"sandbox",checkedAt:new Date().toISOString(),message:"Mock Lithic cards"};await this.request("/v1/cards?page_size=1");return{state:this.config.mode==="live"?"live":"sandbox",checkedAt:new Date().toISOString(),message:this.config.mode==="live"?"Production use requires program and PCI approval":undefined};}
 async execute(op:ProviderOperation,ctx:ProviderContext):Promise<ProviderResult>{if(!this.active)throw new ProviderError({code:"not_initialized",message:"Provider is not initialized",retryable:false});if(this.config.mode==="mock")return this.mock(op,ctx);
  if(op.capability==="spending.card"){
   const type=String(op.input.type??"SINGLE_USE");if(!["SINGLE_USE","MERCHANT_LOCKED"].includes(type))throw new ProviderError({code:"invalid_input",message:"type must be SINGLE_USE or MERCHANT_LOCKED",retryable:false});
   const amount=String(op.input.amountAtomic??"");if(!/^\d+$/.test(amount))throw new ProviderError({code:"invalid_input",message:"amountAtomic must be an integer string",retryable:false});
   const body={type,spend_limit:Number(amount),spend_limit_duration:"FOREVER",state:"OPEN",memo:String(op.input.memo??`Mandate ${ctx.requestId}`),...(this.config.accountToken?{account_token:this.config.accountToken}:{})};
   const r=await this.request("/v1/cards",{method:"POST",headers:this.headers(ctx),body:JSON.stringify(body)});
   // This is the sole one-time credential-bearing response. The daemon must deliver it once and never persist it.
   return{externalId:String(r.token),status:"ready",sensitive:true,data:{token:r.token as JsonValue,pan:r.pan as JsonValue,cvv:r.cvv as JsonValue,expMonth:r.exp_month as JsonValue,expYear:r.exp_year as JsonValue,type:r.type as JsonValue,state:r.state as JsonValue}};
  }
  if(op.capability==="spending.card.revoke"){const token=String(op.input.cardToken);const r=await this.request(`/v1/cards/${token}`,{method:"PATCH",body:JSON.stringify({state:"CLOSED"})});return{externalId:token,status:"revoked",data:this.safeCard(r)};}
  throw new ProviderError({code:"unsupported_operation",message:op.capability,retryable:false});
 }
 private safeCard(r:Record<string,JsonValue>):Record<string,JsonValue>{return{token:r.token??null,state:r.state??null,type:r.type??null,spendLimit:r.spend_limit??null,spendLimitDuration:r.spend_limit_duration??null,created:r.created??null};}
 private mock(op:ProviderOperation,ctx:ProviderContext):ProviderResult{const id=`lithic_mock_${ctx.idempotencyKey??ctx.requestId}`;if(op.capability==="spending.card.revoke")return{externalId:String(op.input.cardToken??id),status:"revoked",data:{state:"CLOSED"}};return{externalId:id,status:"ready",sensitive:true,data:{token:id,pan:"4111111111111111",cvv:"123",expMonth:"12",expYear:"2030",type:op.input.type??"SINGLE_USE",state:"OPEN"}};}
 async retrieveStatus(externalId:string):Promise<ProviderResult>{if(this.config.mode==="mock")return{externalId,status:"ready",data:{token:externalId,state:"OPEN",type:"SINGLE_USE"}};const r=await this.request(`/v1/cards/${externalId}`);return{externalId,status:String(r.state??"unknown").toLowerCase(),data:this.safeCard(r)};}
 async incrementalSync(cursor?:string,_ctx?:ProviderContext):Promise<SyncPage>{if(this.config.mode==="mock")return{events:[],cursor:cursor??"0",hasMore:false};const q=new URLSearchParams({page_size:"100",...(cursor?{starting_after:cursor}:{})});const r=await this.request(`/v1/transactions?${q}`);const data=(r.data??[])as Array<Record<string,JsonValue>>;return{events:data.map(t=>({externalEventId:String(t.token),type:`card.${String(t.status??"transaction").toLowerCase()}`,occurredAt:String(t.updated??t.created??new Date().toISOString()),data:t})),cursor:data.length?String(data.at(-1)?.token):cursor,hasMore:Boolean(r.has_more)};}
 async fullReconciliation(ctx:ProviderContext){return this.incrementalSync(undefined,ctx);}async shutdown(){this.active=false;}
}
